
<?php

/* Generated by FlinkISO API */

App::uses('AppModel', 'Model');

class TblAuditChecklist0V0 extends AppModel {

	public $useTable = 'tbl_audit_checklist_0_v0s';
    public $displayField = 'checklist_title';


	public $validate = array(
		'date_added' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'added_by' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'comments' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
	);

	public $belongsTo = array(
		'CustomTable' => array(
			'className' => 'CustomTable',
			'foreignKey' => 'custom_table_id',
			'conditions' => '',
			'fields' => array('id', 'name','table_name'),
			'order' => ''
		),
		'QcDocument' => array(
			'className' => 'QcDocument',
			'foreignKey' => 'qc_document_id',
			'conditions' => '',
			'fields' => array('id', 'title'),
			'order' => ''
		),
		'Company' => array(
			'className' => 'Company',
			'foreignKey' => 'company_id',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'PreparedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'prepared_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'ApprovedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'approved_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'CreatedBy' => array(
			'className' => 'User',
			'foreignKey' => 'created_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ModifiedBy' => array(
			'className' => 'User',
			'foreignKey' => 'modified_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'AddedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'added_by',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
	);

}