
<?php

/* Generated by FlinkISO API */

App::uses('AppModel', 'Model');

class TblAuditFindings0V0 extends AppModel {

	public $useTable = 'tbl_audit_findings_0_v0s';
    public $displayField = 'finding_number';


	public $validate = array(
		'finding_number' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'audit_start_date' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'audit_end_date' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'auditor' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'auditee' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'finding_type' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'current_status' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'findings' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
	);

	public $belongsTo = array(
		'CustomTable' => array(
			'className' => 'CustomTable',
			'foreignKey' => 'custom_table_id',
			'conditions' => '',
			'fields' => array('id', 'name','table_name'),
			'order' => ''
		),
		'QcDocument' => array(
			'className' => 'QcDocument',
			'foreignKey' => 'qc_document_id',
			'conditions' => '',
			'fields' => array('id', 'title'),
			'order' => ''
		),
		'Company' => array(
			'className' => 'Company',
			'foreignKey' => 'company_id',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'PreparedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'prepared_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'ApprovedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'approved_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'CreatedBy' => array(
			'className' => 'User',
			'foreignKey' => 'created_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ModifiedBy' => array(
			'className' => 'User',
			'foreignKey' => 'modified_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'Auditor' => array(
			'className' => 'Employee',
			'foreignKey' => 'auditor',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'Auditee' => array(
			'className' => 'Employee',
			'foreignKey' => 'auditee',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
	);

	public $customArray = array(
		'findingTypes' => array(
			0=>'Observation',
			1=>' Non-conformity',
		),
		'currentStatuses' => array(
			0=>'Open',
			1=>'Closed',
		),
	);
}