
<?php

/* Generated by FlinkISO API */

App::uses('AppModel', 'Model');

class TblAuditSchedule0V0 extends AppModel {

	public $useTable = 'tbl_audit_schedule_0_v0s';
    public $displayField = 'audit_number';


	public $validate = array(
		'audit_number' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'standard' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'audit_category' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'schedule_start_date' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'scheduled_end_date' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'audit_locations' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'departments_to_be_audited' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'current_status' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'notes' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
	);

	public $belongsTo = array(
		'CustomTable' => array(
			'className' => 'CustomTable',
			'foreignKey' => 'custom_table_id',
			'conditions' => '',
			'fields' => array('id', 'name','table_name'),
			'order' => ''
		),
		'QcDocument' => array(
			'className' => 'QcDocument',
			'foreignKey' => 'qc_document_id',
			'conditions' => '',
			'fields' => array('id', 'title'),
			'order' => ''
		),
		'Company' => array(
			'className' => 'Company',
			'foreignKey' => 'company_id',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'PreparedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'prepared_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'ApprovedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'approved_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'CreatedBy' => array(
			'className' => 'User',
			'foreignKey' => 'created_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ModifiedBy' => array(
			'className' => 'User',
			'foreignKey' => 'modified_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'Standard' => array(
			'className' => 'Standard',
			'foreignKey' => 'standard',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'AuditCategory' => array(
			'className' => 'TblAuditCatetoryV0',
			'foreignKey' => 'audit_category',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'AuditLocation' => array(
			'className' => 'Branch',
			'foreignKey' => 'audit_locations',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'DepartmentsToBeAudited' => array(
			'className' => 'Department',
			'foreignKey' => 'departments_to_be_audited',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
	);

	public $customArray = array(
		'currentStatuses' => array(
			0=>'scheduled',
			1=>'on-going',
			2=>'completed',
			3=>'cancled',
		),
	);
}