
<?php

/* Generated by FlinkISO API */

App::uses('AppModel', 'Model');

class TblCustomerComplaints0V0 extends AppModel {

	public $useTable = 'tbl_customer_complaints_0_v0s';
    public $displayField = 'customer_number';


	public $validate = array(
		'customer' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'complaint_details' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'date_received' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'target_date' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'assigned_to' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'current_status' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'customer_number' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
	);

	public $belongsTo = array(
		'CustomTable' => array(
			'className' => 'CustomTable',
			'foreignKey' => 'custom_table_id',
			'conditions' => '',
			'fields' => array('id', 'name','table_name'),
			'order' => ''
		),
		'QcDocument' => array(
			'className' => 'QcDocument',
			'foreignKey' => 'qc_document_id',
			'conditions' => '',
			'fields' => array('id', 'title'),
			'order' => ''
		),
		'Company' => array(
			'className' => 'Company',
			'foreignKey' => 'company_id',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'PreparedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'prepared_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'ApprovedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'approved_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'CreatedBy' => array(
			'className' => 'User',
			'foreignKey' => 'created_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ModifiedBy' => array(
			'className' => 'User',
			'foreignKey' => 'modified_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'Customer' => array(
			'className' => 'TblCustomerDetails0V0',
			'foreignKey' => 'customer',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'AssignedTo' => array(
			'className' => 'Employee',
			'foreignKey' => 'assigned_to',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
	);

	public $customArray = array(
		'currentStatuses' => array(
			0=>'Open',
			1=>'Closed',
		),
	);
}