
<?php

/* Generated by FlinkISO API */

App::uses('AppModel', 'Model');

class TblCalibration0V0 extends AppModel {

	public $useTable = 'tbl_calibration_0_v0s';
    public $displayField = 'number';


	public $validate = array(
		'number' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'equipement' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'tool_details' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'tool_location' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'calibration_frequency' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'calibration_performed_by' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
	);

	public $belongsTo = array(
		'CustomTable' => array(
			'className' => 'CustomTable',
			'foreignKey' => 'custom_table_id',
			'conditions' => '',
			'fields' => array('id', 'name','table_name'),
			'order' => ''
		),
		'QcDocument' => array(
			'className' => 'QcDocument',
			'foreignKey' => 'qc_document_id',
			'conditions' => '',
			'fields' => array('id', 'title'),
			'order' => ''
		),
		'Company' => array(
			'className' => 'Company',
			'foreignKey' => 'company_id',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'PreparedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'prepared_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'ApprovedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'approved_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'CreatedBy' => array(
			'className' => 'User',
			'foreignKey' => 'created_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ModifiedBy' => array(
			'className' => 'User',
			'foreignKey' => 'modified_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ToolLocation' => array(
			'className' => 'Branch',
			'foreignKey' => 'tool_location',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'CalibrationFrequency' => array(
			'className' => 'Schedule',
			'foreignKey' => 'calibration_frequency',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'CalibrationPerformedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'calibration_performed_by',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
	);

}