
<?php

/* Generated by FlinkISO API */

App::uses('AppModel', 'Model');

class TblDeviceEquipment0V0 extends AppModel {

	public $useTable = 'tbl_device_equipment_0_v0s';
    public $displayField = 'number';


	public $validate = array(
		'number' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'equipment_name' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'location' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'in_service_since' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'equipment_details' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'maintenance_schedule' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
	);

	public $belongsTo = array(
		'CustomTable' => array(
			'className' => 'CustomTable',
			'foreignKey' => 'custom_table_id',
			'conditions' => '',
			'fields' => array('id', 'name','table_name'),
			'order' => ''
		),
		'QcDocument' => array(
			'className' => 'QcDocument',
			'foreignKey' => 'qc_document_id',
			'conditions' => '',
			'fields' => array('id', 'title'),
			'order' => ''
		),
		'Company' => array(
			'className' => 'Company',
			'foreignKey' => 'company_id',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'PreparedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'prepared_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'ApprovedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'approved_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'CreatedBy' => array(
			'className' => 'User',
			'foreignKey' => 'created_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ModifiedBy' => array(
			'className' => 'User',
			'foreignKey' => 'modified_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'Location' => array(
			'className' => 'Branch',
			'foreignKey' => 'location',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'MaintenanceSchedule' => array(
			'className' => 'Schedule',
			'foreignKey' => 'maintenance_schedule',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
	);

}