
<?php

/* Generated by FlinkISO API */

App::uses('AppModel', 'Model');

class TblMrm0V0 extends AppModel {

	public $useTable = 'tbl_mrm_0_v0s';
    public $displayField = 'meeting_number';


	public $validate = array(
		'meeting_number' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'scheduled_date_time' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'proposed_by' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'meeting_details' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'invitees' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'meeting_status' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
	);

	public $belongsTo = array(
		'CustomTable' => array(
			'className' => 'CustomTable',
			'foreignKey' => 'custom_table_id',
			'conditions' => '',
			'fields' => array('id', 'name','table_name'),
			'order' => ''
		),
		'QcDocument' => array(
			'className' => 'QcDocument',
			'foreignKey' => 'qc_document_id',
			'conditions' => '',
			'fields' => array('id', 'title'),
			'order' => ''
		),
		'Company' => array(
			'className' => 'Company',
			'foreignKey' => 'company_id',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'PreparedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'prepared_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'ApprovedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'approved_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'CreatedBy' => array(
			'className' => 'User',
			'foreignKey' => 'created_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ModifiedBy' => array(
			'className' => 'User',
			'foreignKey' => 'modified_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ProposedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'proposed_by',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'Invitee' => array(
			'className' => 'Employee',
			'foreignKey' => 'invitees',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
		'AttaintedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'attainted_by',
			'conditions' => '',
			'fields' => '',
			'order' => ''
		),
	);

/**
 * hasMany associations
 *
 * @var array
 */
	public $hasMany = array(
			'ChdMrm0Child1V1' => array(
				'className' => 'ChdMrm0Child1V1',
				'foreignKey' => 'parent_id',
				'dependent' => false,
				'conditions' => '',
				'fields' => '',
				'order' => array('ChdMrm0Child1V1.sr_no'=>'ASC'),
				'limit' => '',
				'offset' => '',
				'exclusive' => '',
				'finderQuery' => '',
				'counterQuery' => ''
			),
	);
	public $customArray = array(
		'meetingStatuses' => array(
			0=>'Scheduled',
			1=>'Conducted',
			2=>'Cancled',
		),
	);
}