
<?php

/* Generated by FlinkISO API */

App::uses('AppModel', 'Model');

class TblSupplierDetails0V0 extends AppModel {

	public $useTable = 'tbl_supplier_details_0_v0s';
    public $displayField = 'supplier_number';


	public $validate = array(
		'name' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'supplier_address' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'supplier_phone' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'supplier_email' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'supplier_company_type' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
		'supplier_number' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
			),
		),
	);

	public $belongsTo = array(
		'CustomTable' => array(
			'className' => 'CustomTable',
			'foreignKey' => 'custom_table_id',
			'conditions' => '',
			'fields' => array('id', 'name','table_name'),
			'order' => ''
		),
		'QcDocument' => array(
			'className' => 'QcDocument',
			'foreignKey' => 'qc_document_id',
			'conditions' => '',
			'fields' => array('id', 'title'),
			'order' => ''
		),
		'Company' => array(
			'className' => 'Company',
			'foreignKey' => 'company_id',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'PreparedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'prepared_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'ApprovedBy' => array(
			'className' => 'Employee',
			'foreignKey' => 'approved_by',
			'conditions' => '',
			'fields' => array('id', 'name'),
			'order' => ''
		),
		'CreatedBy' => array(
			'className' => 'User',
			'foreignKey' => 'created_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
		'ModifiedBy' => array(
			'className' => 'User',
			'foreignKey' => 'modified_by',
			'conditions' => '',
			'fields' => array('id', 'username'),
			'order' => ''
		),
	);

	public $customArray = array(
		'supplierCompanyTypes' => array(
			0=>'Self-owned',
			1=>' Partnership Firm',
			2=>' LLP',
			3=>' Pvt Ltd.',
			4=>' Ltd. ',
		),
	);
}