<?php
App::uses('AppController', 'Controller');
App::uses('Folder', 'Utility');
App::uses('File', 'Utility');

/* Generated by FlinkISO API */

class TblCalibration0V0sController extends AppController {

	public $components = array('Paginator');

	public function _get_system_table_id() {
		$this->loadModel('SystemTable');
		$this->SystemTable->recursive = -1;
		$systemTableId = $this->SystemTable->find('first', array('conditions' => array('SystemTable.system_name' => $this->request->params['controller'])));
		return $systemTableId['SystemTable']['id'];
	}

	public function _commons($creator = null){
		
		if($this->action == 'view' || $this->action == 'edit' )$this->set('approvals',$this->get_approvals());
	    	$companies = $this->TblCalibration0V0->Company->find('list',array('conditions'=>array('Company.publish'=>1,'Company.soft_delete'=>0)));
		$preparedBies = $approvedBies = $this->TblCalibration0V0->PreparedBy->find('list',array('conditions'=>array('PreparedBy.publish'=>1,'PreparedBy.soft_delete'=>0)));
		$createdBies = $modifiedBies = $this->TblCalibration0V0->CreatedBy->find('list',array('conditions'=>array('CreatedBy.publish'=>1,'CreatedBy.soft_delete'=>0)));		
		$count = $this->TblCalibration0V0->find('count');
		$published = $this->TblCalibration0V0->find('count',array('conditions'=>array('TblCalibration0V0.publish'=>1)));
		$unpublished = $this->TblCalibration0V0->find('count',array('conditions'=>array('TblCalibration0V0.publish'=>0)));
		$this->set(compact('companies', 'preparedBies', 'approvedBies', 'createdBies', 'modifiedBies','count','publish','unpublished'));

$toolLocations = $this->TblCalibration0V0->ToolLocation->find('list',array('conditions'=> array ('ToolLocation.publish' => 1,'ToolLocation.soft_delete'=>0)));
$calibrationFrequencies = $this->TblCalibration0V0->CalibrationFrequency->find('list',array('conditions'=> array ('CalibrationFrequency.publish' => 1,'CalibrationFrequency.soft_delete'=>0)));
$calibrationPerformedBies = $this->TblCalibration0V0->CalibrationPerformedBy->find('list',array('conditions'=> array ('CalibrationPerformedBy.publish' => 1,'CalibrationPerformedBy.soft_delete'=>0)));		$this->set('customArray',$this->TblCalibration0V0->customArray);		$this->set(compact('toolLocations','calibrationFrequencies','calibrationPerformedBies'));
	
		if($this->request->params['named']['approval_id']){						
			$this->get_approval($this->request->params['named']['approval_id'],$creator);
			$this->_get_approval_comnments($this->request->params['named']['approval_id'],$creator);
		}
	
		$this->_get_approver_list();
		$this->_get_hasMany();

		// get hasMay
		$thisTable = $this->TblCalibration0V0->CustomTable->find('first',array('recursive'=>-1,'conditions'=>array('CustomTable.id'=>$this->request->params['named']['custom_table_id'])));
		if($thisTable){
			// find linked tables
			$linkedTables = $this->TblCalibration0V0->CustomTable->find('all',array('recursive'=>-1,'conditions'=>array(
				// 'CustomTable.publish'=>1,
				// 'CustomTable.table_locked'=>0,
				'CustomTable.custom_table_id'=>$this->request->params['named']['custom_table_id'])));
			$this->set('linkedTables',$linkedTables);
		}

		if($this->request->params['named']['qc_document_id'])$this->_qc_document_header($this->request->params['named']['qc_document_id']);	
	}

	public function index() {
		if($this->request->params['named']['parent_record_id']){
				$tblCalibration0V0s= $this->TblCalibration0V0->find('all',array('conditions'=>array('TblCalibration0V0.parent_id'=>$this->request->params['named']['parent_record_id'])));
				$this->set('tblCalibration0V0s', $tblCalibration0V0s);
				$this->_qc_document_header($this->request->params['named']['qc_document_id']);
				$this->_commons($this->Session->read('User.id'));
			}else{

			$conditions = $this->_check_request();
			$this->paginate = array('order'=>array('TblCalibration0V0.sr_no'=>'DESC'),'conditions'=>array($conditions));
		
			$this->TblCalibration0V0->recursive = 0;
			$this->set('tblCalibration0V0s', $this->paginate());
			
			$this->_get_count();

			if(!isset($this->request->params['named']['qc_document_id'])){
				$this->Session->setFlash(__('Table is without any QC Document'));
				// $this->redirect(array('controller'=>'custom_tables', 'action' => 'index'));
			}else{
			$this->_qc_document_header($this->request->params['named']['qc_document_id']);
}
		
	$this->_commons($this->Session->read('User.id'));
		}
	}

	public function view($id = null) {
		if (!$this->TblCalibration0V0->exists($id)) {
			throw new NotFoundException(__('Invalid Record'));
		}
		$options = array('conditions' => array('TblCalibration0V0.' . $this->TblCalibration0V0->primaryKey => $id));
		$tblCalibration0V0 = $this->TblCalibration0V0->find('first', $options);
		$this->set('tblCalibration0V0', $this->TblCalibration0V0->find('first', $options));
		$this->_qc_document_header($tblCalibration0V0['TblCalibration0V0']['qc_document_id']);
		$this->_commons($this->Session->read('User.id'));

		$thisTable = $this->TblCalibration0V0->CustomTable->find('first',array('recursive'=>-1,'conditions'=>array('CustomTable.id'=>$tblCalibration0V0['TblCalibration0V0']['custom_table_id'])));
		if($thisTable){

			// find linked tables
			$linkedTables = $this->TblCalibration0V0->CustomTable->find('all',array('recursive'=>-1,'conditions'=>array(
				// 'CustomTable.publish'=>1,
				// 'CustomTable.table_locked'=>0,
				'CustomTable.custom_table_id'=>$thisTable['CustomTable']['id'])));
			$this->set('linkedTables',$linkedTables);
		}

		$this->set('fileEdit',$this->_fetch_file($id));
	}

	public function add() {
		if($this->request->is('post')){$this->_add();}		
		$this->_commons($this->Session->read('User.id'));
		if($this->_show_approvals()){$this->set(array('showApprovals' => $this->_show_approvals()));}
        	$this->set('fileEdit',$this->_prepare_update());				
	}


	public function edit($id = null) {
		if(!$this->TblCalibration0V0->exists($id)){throw new NotFoundException(__('Invalid record'));}		
		
		if (($this->request->is('post') || $this->request->is('put')) &&  isset($this->request->data[$this->modelClass])) {
			$this->_add();
		}else{
			$options = array('conditions' => array('TblCalibration0V0.' . $this->TblCalibration0V0->primaryKey => $id));
			$this->request->data = $this->TblCalibration0V0->find('first', $options);
		}
		$this->_commons($this->Session->read('User.id'));	
		if($this->_show_approvals()) {$this->set(array('showApprovals' => $this->_show_approvals()));}		
		$this->set('fileEdit',$this->_fetch_file($id));		
	}
}