DELETE FROM histories
WHERE id IN (
    'SIM-BLIND-HISTORY-DB65-001',
    'SIM-BLIND-HISTORY-CNAS-001',
    'SIM-BLIND-HISTORY-AUTH-001',
    'SIM-BLIND-HISTORY-RAW-001'
);

DELETE FROM approvals
WHERE id = 'SIM-BLIND-APPROVAL-AUTH-001';

DELETE FROM record_form_instances
WHERE id IN (
    'SIM-BLIND-RPT-DB65-001',
    'SIM-BLIND-RPT-CNAS-001',
    'SIM-BLIND-RPT-AUTH-001',
    'SIM-BLIND-RAW-SEM-001'
);

DELETE FROM employee_appointments
WHERE id = 'SIM-BLIND-APPT-SIGNER-001';

DELETE FROM users
WHERE id = 'SIM-BLIND-USER-SIGNER-001';

DELETE FROM employees
WHERE id = 'SIM-BLIND-EMP-SIGNER-001';

DELETE FROM record_form_templates
WHERE id IN (
    'SIM-BLIND-TPL-RPT-001',
    'SIM-BLIND-TPL-RAW-001'
);
