-- 全项目统一更正层。
-- 原业务记录不覆盖、不删除；申请批准后只向更正账本追加字段差异。

CREATE TABLE IF NOT EXISTS `qms_governed_change_requests` (
  `id` varchar(40) NOT NULL,
  `company_id` varchar(40) NOT NULL,
  `subject_type` varchar(80) NOT NULL,
  `subject_id` varchar(40) NOT NULL,
  `subject_label` varchar(255) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `change_kind` varchar(30) NOT NULL DEFAULT 'correction',
  `field_name` varchar(100) NOT NULL,
  `field_label` varchar(255) NOT NULL,
  `original_value` text,
  `proposed_value` text,
  `reason` text NOT NULL,
  `requested_by` varchar(40) DEFAULT NULL,
  `requested_at` datetime NOT NULL,
  `decided_by` varchar(40) DEFAULT NULL,
  `decided_at` datetime DEFAULT NULL,
  `decision_comment` text,
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(40) DEFAULT NULL,
  `modified_by` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `subject_lookup` (`company_id`,`subject_type`,`subject_id`),
  KEY `pending_lookup` (`company_id`,`status`,`requested_at`),
  KEY `field_lookup` (`subject_type`,`subject_id`,`field_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_governed_changes` (
  `id` varchar(40) NOT NULL,
  `company_id` varchar(40) NOT NULL,
  `request_id` varchar(40) NOT NULL,
  `subject_type` varchar(80) NOT NULL,
  `subject_id` varchar(40) NOT NULL,
  `subject_label` varchar(255) NOT NULL,
  `change_kind` varchar(30) NOT NULL DEFAULT 'correction',
  `field_name` varchar(100) NOT NULL,
  `field_label` varchar(255) NOT NULL,
  `old_value` text,
  `new_value` text,
  `reason` text NOT NULL,
  `registered_by` varchar(40) DEFAULT NULL,
  `registered_at` datetime NOT NULL,
  `approved_by` varchar(40) DEFAULT NULL,
  `approved_at` datetime NOT NULL,
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(40) DEFAULT NULL,
  `modified_by` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `request_once` (`request_id`),
  KEY `subject_lookup` (`company_id`,`subject_type`,`subject_id`,`registered_at`),
  KEY `field_lookup` (`subject_type`,`subject_id`,`field_name`,`registered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
