CREATE TABLE IF NOT EXISTS `quality_review_projects` (
  `id` varchar(64) NOT NULL,
  `company_id` varchar(64) NOT NULL DEFAULT '',
  `project_code` varchar(120) NOT NULL,
  `title` varchar(255) NOT NULL,
  `project_type` varchar(64) NOT NULL,
  `scope_label` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(40) NOT NULL DEFAULT 'active',
  `conclusion` text NULL,
  `owner_role` varchar(64) NOT NULL DEFAULT '',
  `owner_user_id` varchar(64) NOT NULL DEFAULT '',
  `due_date` date NULL,
  `summary_json` mediumtext NULL,
  `accepted_at` datetime NULL,
  `accepted_by` varchar(64) NOT NULL DEFAULT '',
  `publish` tinyint(1) NOT NULL DEFAULT 1,
  `soft_delete` tinyint(1) NOT NULL DEFAULT 0,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_quality_review_project_code` (`company_id`, `project_code`, `soft_delete`),
  KEY `idx_quality_review_project_status` (`status`, `project_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `quality_review_tasks` (
  `id` varchar(64) NOT NULL,
  `project_id` varchar(64) NOT NULL,
  `title` varchar(255) NOT NULL,
  `task_type` varchar(80) NOT NULL,
  `severity` varchar(20) NOT NULL DEFAULT 'warning',
  `status` varchar(40) NOT NULL DEFAULT 'open',
  `source_model` varchar(120) NOT NULL DEFAULT '',
  `source_id` varchar(120) NOT NULL DEFAULT '',
  `assigned_role` varchar(64) NOT NULL DEFAULT '',
  `assigned_user_id` varchar(64) NOT NULL DEFAULT '',
  `due_date` date NULL,
  `action_url` varchar(512) NOT NULL DEFAULT '',
  `evidence_summary` text NULL,
  `payload_json` mediumtext NULL,
  `completed_at` datetime NULL,
  `completed_by` varchar(64) NOT NULL DEFAULT '',
  `publish` tinyint(1) NOT NULL DEFAULT 1,
  `soft_delete` tinyint(1) NOT NULL DEFAULT 0,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_quality_review_task_source` (`project_id`, `task_type`, `source_model`, `source_id`, `soft_delete`),
  KEY `idx_quality_review_task_status` (`status`, `severity`),
  KEY `idx_quality_review_task_assignee` (`assigned_role`, `assigned_user_id`, `due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `quality_review_events` (
  `id` varchar(64) NOT NULL,
  `project_id` varchar(64) NOT NULL,
  `task_id` varchar(64) NOT NULL DEFAULT '',
  `event_type` varchar(60) NOT NULL,
  `old_status` varchar(40) NOT NULL DEFAULT '',
  `new_status` varchar(40) NOT NULL DEFAULT '',
  `note` text NULL,
  `created_by` varchar(64) NOT NULL DEFAULT '',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_quality_review_event_project` (`project_id`, `created`),
  KEY `idx_quality_review_event_task` (`task_id`, `created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
