CREATE TABLE IF NOT EXISTS `qms_sources` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `source_code` varchar(80) NOT NULL COMMENT '依据编号',
  `name` varchar(300) NOT NULL,
  `source_type` varchar(60) DEFAULT 'external_standard',
  `version` varchar(80) DEFAULT NULL,
  `effective_date` date DEFAULT NULL,
  `attachment_file_path` varchar(500) DEFAULT NULL,
  `attachment_file_name` varchar(255) DEFAULT NULL,
  `status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'draft',
  `review_note` text,
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `source_code` (`source_code`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_clauses` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `source_id` varchar(36) NOT NULL,
  `parent_id` varchar(36) DEFAULT NULL,
  `clause_number` varchar(80) NOT NULL,
  `title` varchar(500) NOT NULL,
  `level` tinyint(2) DEFAULT 1,
  `page_number` int DEFAULT NULL,
  `locator` varchar(255) DEFAULT NULL,
  `applicability` enum('applicable','not_applicable','conditional') DEFAULT 'applicable',
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `summary` text,
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `source_clause` (`source_id`,`clause_number`),
  KEY `parent_id` (`parent_id`),
  KEY `review_status` (`review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_clause_texts` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `clause_id` varchar(36) NOT NULL,
  `source_id` varchar(36) NOT NULL,
  `clause_number` varchar(80) NOT NULL,
  `original_text` mediumtext NOT NULL,
  `locator` varchar(255) DEFAULT NULL,
  `page_number` int DEFAULT NULL,
  `text_hash` varchar(64) DEFAULT NULL,
  `extraction_method` varchar(80) DEFAULT 'manual',
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `review_note` text,
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `clause_text` (`clause_id`),
  KEY `source_clause` (`source_id`,`clause_number`),
  KEY `review_status` (`review_status`),
  KEY `text_hash` (`text_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_requirement_elements` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `element_code` varchar(80) NOT NULL COMMENT '体系要素编号，优先取现用质量手册附录16的手册章节号',
  `name` varchar(300) NOT NULL,
  `manual_section` varchar(80) DEFAULT NULL,
  `source_basis` varchar(160) DEFAULT NULL,
  `summary` text,
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `element_code` (`element_code`),
  KEY `manual_section` (`manual_section`),
  KEY `review_status` (`review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_element_clause_mappings` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `element_id` varchar(36) DEFAULT NULL,
  `element_code` varchar(80) NOT NULL,
  `source_id` varchar(36) DEFAULT NULL,
  `source_code` varchar(80) NOT NULL,
  `clause_number` varchar(120) NOT NULL,
  `clause_title` varchar(500) DEFAULT NULL,
  `mapping_basis` enum('equivalent','partial','supplement','reference') DEFAULT 'equivalent',
  `mapping_source` varchar(160) DEFAULT NULL,
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `element_source_clause` (`element_code`,`source_code`,`clause_number`),
  KEY `element_id` (`element_id`),
  KEY `source_id` (`source_id`),
  KEY `review_status` (`review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_positions` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `code` varchar(100) NOT NULL,
  `name` varchar(200) NOT NULL,
  `department_hint` varchar(200) DEFAULT NULL,
  `source` varchar(120) DEFAULT NULL,
  `description` text,
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `review_status` (`review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_responsibility_matrix` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `clause_id` varchar(36) DEFAULT NULL,
  `clause_number` varchar(80) DEFAULT NULL,
  `position_id` varchar(36) DEFAULT NULL,
  `position_name` varchar(200) DEFAULT NULL,
  `responsibility_type` enum('decision_owner','organizer','participant') NOT NULL,
  `raw_symbol` varchar(20) DEFAULT NULL,
  `source_style` varchar(80) DEFAULT NULL,
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `clause_number` (`clause_number`),
  KEY `position_id` (`position_id`),
  KEY `responsibility_type` (`responsibility_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_document_sections` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `document_id` varchar(36) DEFAULT NULL,
  `parent_id` varchar(36) DEFAULT NULL,
  `section_number` varchar(80) NOT NULL,
  `title` varchar(500) NOT NULL,
  `level` tinyint(2) DEFAULT 1,
  `summary` text,
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `document_id` (`document_id`),
  KEY `section_number` (`section_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_trace_links` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `source_type` enum('clause','requirement_element','document_section','document','record_form_template','business_module','quality_objective','position') NOT NULL,
  `source_id` varchar(36) DEFAULT NULL,
  `source_key` varchar(120) DEFAULT NULL,
  `target_type` enum('clause','requirement_element','document_section','document','record_form_template','business_module','quality_objective','position') NOT NULL,
  `target_id` varchar(36) DEFAULT NULL,
  `target_key` varchar(120) DEFAULT NULL,
  `relation_type` varchar(80) DEFAULT 'maps_to',
  `evidence_note` text,
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `source_lookup` (`source_type`,`source_key`),
  KEY `target_lookup` (`target_type`,`target_key`),
  KEY `review_status` (`review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `qms_trace_links`
  MODIFY COLUMN `source_type` enum('clause','requirement_element','document_section','document','record_form_template','business_module','quality_objective','position') NOT NULL,
  MODIFY COLUMN `target_type` enum('clause','requirement_element','document_section','document','record_form_template','business_module','quality_objective','position') NOT NULL;

CREATE TABLE IF NOT EXISTS `qms_quality_policies` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `title` varchar(300) NOT NULL,
  `policy_text` text NOT NULL,
  `version` varchar(80) DEFAULT NULL,
  `effective_date` date DEFAULT NULL,
  `source_document_id` varchar(36) DEFAULT NULL,
  `is_current` tinyint(1) DEFAULT 0,
  `management_review_input` tinyint(1) DEFAULT 1,
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'draft',
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `is_current` (`is_current`),
  KEY `review_status` (`review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_quality_objectives` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `policy_id` varchar(36) DEFAULT NULL,
  `year` smallint DEFAULT NULL,
  `department_id` varchar(36) DEFAULT NULL,
  `position_id` varchar(36) DEFAULT NULL,
  `title` varchar(300) NOT NULL,
  `metric_name` varchar(200) DEFAULT NULL,
  `target_value` varchar(120) DEFAULT NULL,
  `unit` varchar(40) DEFAULT NULL,
  `statistic_cycle` enum('monthly','quarterly','semiannual','annual','event') DEFAULT 'annual',
  `responsible_department` varchar(200) DEFAULT NULL,
  `responsible_position` varchar(200) DEFAULT NULL,
  `management_review_input` tinyint(1) DEFAULT 1,
  `review_status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'draft',
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `year` (`year`),
  KEY `department_id` (`department_id`),
  KEY `review_status` (`review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_import_batches` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `name` varchar(300) NOT NULL,
  `batch_type` varchar(80) NOT NULL,
  `source_path` varchar(500) DEFAULT NULL,
  `source_hash` char(40) DEFAULT NULL,
  `status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `total_candidates` int DEFAULT 0,
  `published_count` int DEFAULT 0,
  `rejected_count` int DEFAULT 0,
  `obsolete_count` int DEFAULT 0,
  `note` text,
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `batch_type` (`batch_type`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `qms_import_candidates` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `batch_id` varchar(36) NOT NULL,
  `candidate_type` varchar(80) NOT NULL,
  `source_code` varchar(100) DEFAULT NULL,
  `source_locator` varchar(255) DEFAULT NULL,
  `payload` longtext NOT NULL,
  `status` enum('candidate','draft','pending_review','published','rejected','obsolete') DEFAULT 'pending_review',
  `review_note` text,
  `published_record_id` varchar(36) DEFAULT NULL,
  `published_at` datetime DEFAULT NULL,
  `publish` tinyint(1) DEFAULT 1,
  `soft_delete` tinyint(1) DEFAULT 0,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `batch_id` (`batch_id`),
  KEY `candidate_type` (`candidate_type`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
